### ISSUE TITLE
Documentation Import error on package name

### ISSUE THREAD

**Issue by cr8ivecodesmith** [scrapinghub/scrapy-crawlera#3]
Installed from `pypi`. Readme here says to use `crawlera.CrawleraMiddleware` which produces an import error.

[Documentation](http://doc.scrapinghub.com/crawlera.html#using-crawlera-with-scrapy) in ScrapingHub says to use `scrapy_crawlera.CrawleraMiddleware` works.

Perhaps the package in `pypi` is in `scrapy_crawlera`.

**Comment by pablohoffman** [comment]
Are you sure?

I see `scrapy_crawlera` in the example code in the scrapinghub documentation page:
http://doc.scrapinghub.com/crawlera.html#using-crawlera-with-scrapy

**Comment by cr8ivecodesmith** [comment]
That's correct. The doc in scrapinghub works when I install the `scrapy-crawlera` package from pip. However the `README` on this repo will cause an import error when followed.

Doc in scrapinghub says: `scrapy_crawlera.CrawleraMiddleware`
`README` in this repo says: `crawlera.CrawleraMiddleware`

When I looked closer, the home page configured in the pypi page points here: https://github.com/scrapinghub/crawlera-tools/tree/master/scrapy-crawlera
Which contains the working code sample. It gets confusing though since the package on that link and this repo are named differently but are essentially the same project.
